### ISSUE TITLE
page title

### ISSUE THREAD

**Issue by Tommy0412** [M-YasirGhaffar/React-movie-streaming-app#1]
Hello, sorry to bother you, how to change page title? for example for all movies i want something like watch (movie.name) online free.
how i can achivet that?

**Comment by M-YasirGhaffar** [comment]
You can change the document title in this component **src/components/MovieDetail.jsx** like this:

  useEffect(() => {
    document.title = `Watch ${movie.title} online free';
  }, [movie]);

Make sure you use the useEffect after fetchMovieDetails function
